[project]
name = "batchedllm"
readme = "README.md"
keywords = ["batched", "LLM"]
authors = [
    {name = "Danil Kireev", email="nenil@nenil.dev"},
    {name = "Daniil Larionov", email="rexhaif.io@gmail.com"},
]
license = "MIT"
dynamic = [
  "version",
  "description",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Topic :: Utilities",
    "Typing :: Typed",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 3 - Alpha",
]
requires-python = ">=3.12"
dependencies = [
    "tqdm>=4.67.3",
]

[project.optional-dependencies]
all = [
    "batchedllm[openai]"
]
openai = [
    "openai>=2.41.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    {include-group = "lint"},
    {include-group = "test"}
]
lint = [
    "ruff>=0.15.15",
    "ty>=0.0.38",
]
test = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.1.0",
]

[build-system]
requires = [
  "hatchling>=1.32.0", 
  "hatch-docstring-description", # https://github.com/pyproject-nix/build-system-pkgs/issues/176
]
build-backend = "hatchling.build"

[project.scripts]
lint = "ruff:check"
format = "ruff:format"

[tool.hatch.version]
path = "src/batchedllm/__init__.py"

[tool.hatch.metadata.hooks.docstring-description] # removed for uv

[tool.pytest]
addopts = ["--import-mode=importlib", "--cov=batchedllm", "--cov-report=xml", "--cov-report=term-missing", "--cov-report=markdown"]
asyncio_mode = "auto"

[project.urls]
repository = "https://github.com/batchedllm/batchedllm"
