[project]
name = "batchedllm"
readme = "README.md"
keywords = ["batched", "LLM"]
authors = [
    {name = "Danil Kireev", email="nenil@nenil.dev"},
    {name = "Daniil Larionov", email="rexhaif.io@gmail.com"},
]
license = "MIT"
dynamic = ["version", "description"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Topic :: Utilities",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
requires-python = ">=3.12"
dependencies = [
    "tqdm>=4.67.3",
]

[project.optional-dependencies]
openai = [
    "openai>=2.32.0",
]

[dependency-groups]
dev = [
    "coverage>=7.14.0",
    "pre-commit>=4.5.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.15.13",
    "ty>=0.0.35",
]

# more meta
[project.urls]
repository = "https://github.com/batchedllm/batchedllm"

# build
[build-system]
requires = ["hatchling", "hatch-docstring-description"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/batchedllm/__init__.py"

[tool.hatch.metadata.hooks.docstring-description]

# tools
[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = ["--import-mode=importlib"]
asyncio_mode = "auto"

[tool.coverage.run]
omit = [
    "tests/**/*",
]
