name: Release on Github and upload to PyPI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v7

      - run: uv sync --locked --all-extras --dev

      - run: uv build

      - shell: uv run {0}
        env:
          GIT_TAG: ${{ github.ref_name }}
        run: |
          import os, sys
          from batchedllm import __version__
          sys.exit(__version__ == os.environ["GIT_TAG"])

      - uses: actions/upload-artifact@v4
        with:
          name: release-dist
          path: dist/

  gh-release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dist
          path: dist/

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write # for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/p/batchedllm

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dist
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
